### ISSUE TITLE
install on Linux

### ISSUE THREAD

**Issue by mfaridi1394** [hiroara/bunshin-no-jutsu#1]
I want to install it by build, but when I run this command
go install github.com/hiroara/bunshin-no-jutsu
I see this error
can't load package: package github.com/hiroara/bunshin-no-jutsu: cannot find package "github.com/hiroara/bunshin-no-jutsu" in any of:
	/usr/lib/go-1.10/src/github.com/hiroara/bunshin-no-jutsu (from $GOROOT)

**Comment by hiroara** [comment]
Sorry, the direction on the readme seems wrong.
Instead, does this command `go get -u github.com/hiroara/bunshin-no-jutsu/bunshin` work?

**Comment by mfaridi1394** [comment]
> go get -u github.com/hiroara/bunshin-no-jutsu/bunshin

thanks, I have it on Linux box.

**Comment by hiroara** [comment]
Thank you for checking! I reflected the change to `README.md` :)
I'll close this issue. Please let me know if there is any problem.
